### PR TITLE
Laravel 5.2 - conflict with multiple DB connections

### PR DESCRIPTION
**Pull request by seltix5**
hi,
after 3 days searching for a problem using multiple DB connection i finnaly found the root problem here :

https://github.com/AgelxNash/SEOPagination/blob/laravel-5.2/src/PaginationServiceProvider.php#L35

because the "registar" functions uses "singleton" when i try to create a new connection L5.2 always returns the previous connection...

solution for this please?

maybe change "singleton" to "bind" ?

thanks

### CODE REVIEW

**Comment by seltix5** [comment]
i dont understand what append here... what this fixed? i dont see any change in the code... thanks

**Comment by AgelxNash** [comment]
Look laravel-5.2 branch

**Comment by seltix5** [comment]
I dont don't see any changes on the code :-\ sorry maybe im not locking in the right place? I use my link on the OP.

**Comment by AgelxNash** [comment]
https://github.com/AgelxNash/SEOPagination/tree/laravel-5.2

**Comment by seltix5** [comment]
i dont see any changes on the code, how was this problem solved?
thanks

**Comment by seltix5** [comment]
i just reported a problem that i found in my first comment, i dont know whats the best way to solve it. i dont really know what was the result of this "pull request" but what i wanted was to correct this issue in the L5.2 version and i dont see any changer nor a new version to update (composer update)...
thanks

**Comment by AgelxNash** [comment]
maybe composer cache?
```
composer require agelxnash/seopagination:5.2.*@dev
```

**Comment by seltix5** [comment]
i already have your package installed, so it should be just a update

**Comment by AgelxNash** [comment]
Change agelxnash/seopagination:**5.1.*@dev** to agelxnash/seopagination:**5.2.*@dev**

**Comment by seltix5** [comment]
i am already using 5.2....

"agelxnash/seopagination": "5.2.*@dev",

**Comment by seltix5** [comment]
i probably dint create this pull request correctly and create some confusion here =/
this is my first PR...

**Pull request merged**
