### PR TITLE
Add the "url/?page1" request to error cases

### PR DESCRIPTION
**Pull request by Gael42**
Add the "url/?page=1" request to error cases so that GET "url/?page=1" is redirected to url/

( also thanks for sharing your work, that was just what i was looking for :-D )

### CODE REVIEW

**Comment by Gael42** [comment]
Even if no links pointing to it was generated, the `url/?page=1` URL was still accessible and this may be an double content issue for SEO if google comes to catch this url, and i dont want to create a specific rule for it, while this little change in your package makes sense and is much cleaner. Do you agree ?

**Comment by AgelxNash** [comment]
Yes, I agree. But I think it's not correct to `action_on_error = out`
Maybe make a special provision for this case?

``` php
if(1 == $cPage) $this->setActionOnError('first');
if((1 == (int)$request) || ($this->isEmpty() && 1!=$cPage) || (1==$cPage && !is_null($request) && (int)$request!=$cPage)){
  /* switch action */
}
```

**Comment by Gael42** [comment]
Yes, you're right ! I just did this in my fork, you can accept my pull request if it fit your expectations.

**Comment by AgelxNash** [comment]
Thanks

**Pull request merged**
